import { Roboto } from "next/font/google";
import { AppProvider } from "@/Components/AppContext/AppProvider";
import { Toaster } from "react-hot-toast";
import NavBar from "@/Components/Layout/NavBar/NavBar";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.className} min-h-screen w-full text-xl  `}>
        <AppProvider>
          <Toaster />
          <NavBar />
          <main className="p-8">{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
